
spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  redis:
    port: 7379
    host: 106.15.2.32
    connect-timeout: 5000
    jedis:
      pool:
        max-idle: 10
        max-wait: -1
        min-idle: 5
server:
  port: 8888
  error:
    include-message: ALWAYS
    include-stacktrace: NEVER